version: '3.8'

services:
  catalog-rest-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3010:3000"
    restart: unless-stopped
