version: '3.8'

services:
  catalog-rest-server:
    image: registry.hollanderconsulting.nl/catalog-rest-server:latest
    env_file: .env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    # Keep the direct port mapping for backward compatibility
    ports:
      - "3010:3000"
    restart: unless-stopped
    networks:
      - catalog-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Uncomment these lines when you have SSL certificates
      # - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - catalog-rest-server
    restart: unless-stopped
    networks:
      - catalog-network

networks:
  catalog-network:
    driver: bridge
