# Docker Compose configuration for local deployment
# - catalog-rest-server: Node.js application running on port 3000

services:
  catalog-rest-server:
    image: registry.hollanderconsulting.nl/catalog-rest-server:v${VERSION:-0.1.23}
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - HOST=0.0.0.0
      - NEXT_PUBLIC_APP_VERSION=${VERSION:-0.1.23}
      - NEXT_PUBLIC_DEFAULT_THEME=dark
    ports:
      - "3000:3000"
    restart: unless-stopped
