version: '3.8'

services:
  catalog-rest-server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount source code for development
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  # Optional: Add development service with hot reloading
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
