version: '3.8'

services:
  catalog-rest-server:
    image: registry.hollanderconsulting.nl/catalog-rest-server:latest
    env_file: .env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    restart: unless-stopped
